server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: file:///D:/TmaxEducation/MSA/git-local-repo
          uri: https://github.com/ojiwoong/my-spring-cloud-config
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: info, health, busrefresh, refresh, metrics
